import os
import requests
from bs4 import BeautifulSoup

def gather_headshot_urls(html_content):
    headshots = []  # Lista do przechowywania tuple (url, tytuł)

    soup = BeautifulSoup(html_content, 'html.parser')

    # Znajdź tabelę zawierającą headshoty
    table = soup.find('table', class_='wikitable')
    if table:
        # Iteracja przez każdy wiersz w tabeli
        for row in table.find_all('tr'):
            # Iteracja przez wszystkie komórki w wierszu
            for cell in row.find_all('td'):
                figure = cell.find('figure')
                if figure:
                    img_tag = figure.find('img')
                    if img_tag and 'src' in img_tag.attrs:
                        img_url = img_tag['src']  # Link do obrazka
                        title = figure.find('p', class_='caption').find('a').text  # Tytuł postaci
                        headshots.append((img_url, title))

    return headshots

def download_image(image_url, folder, title):
    # Przygotowanie nazwy pliku
    file_name = f"{title.replace(' ', '_')}.png"  # Zastąp spacje podkreśleniami
    file_path = os.path.join(folder, file_name)

    print(f"Próbuję pobrać: {image_url}")
    try:
        response = requests.get(image_url, timeout=10)
        response.raise_for_status()

        with open(file_path, 'wb') as f:
            f.write(response.content)

        print(f"Pobrano: {file_path}")
    except Exception as e:
        print(f"Błąd podczas pobierania obrazu: {image_url}, błąd: {e}")

if __name__ == "__main__":
    html_content = '''<table class="wikitable" data-index-number="0">
<tbody><tr>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/7/7e/2220.png/revision/latest?cb=20160123194957" class="image"><img alt="2220" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/7/7e/2220.png/revision/latest?cb=20160123194957" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2220.png" data-image-key="2220.png" data-relevant="0"></a> 	 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Freddy" class="mw-redirect" title="Adventure Freddy">Freddy Fazbear</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/ed/ZLC6R6a.png/revision/latest?cb=20160123211706" class="image"><img alt="ZLC6R6a" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/ed/ZLC6R6a.png/revision/latest?cb=20160123211706" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="ZLC6R6a.png" data-image-key="ZLC6R6a.png" data-relevant="0"></a> 	 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Bonnie" title="Adventure Bonnie">Bonnie</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b1/Chica.png/revision/latest?cb=20151214210514" class="image"><img alt="Chica" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b1/Chica.png/revision/latest?cb=20151214210514" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Chica.png" data-image-key="Chica.png" data-relevant="0"></a> 	 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Chica" title="Adventure Chica">Chica</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/Foxy.png/revision/latest?cb=20151214210514" class="image"><img alt="Foxy" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/Foxy.png/revision/latest?cb=20151214210514" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Foxy.png" data-image-key="Foxy.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/Foxy.png/revision/latest?cb=20151214210514"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/Foxy.png/revision/latest?cb=20151214210514" class="image"><img alt="Foxy" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/Foxy.png/revision/latest?cb=20151214210514" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Foxy.png" data-image-key="Foxy.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/Foxy.png/revision/latest?cb=20151214210514" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Foxy" title="Adventure Foxy">Foxy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/c/c3/2863.png/revision/latest?cb=20160123230737" class="image"><img alt="2863" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/c/c3/2863.png/revision/latest?cb=20160123230737" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2863.png" data-image-key="2863.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/c/c3/2863.png/revision/latest?cb=20160123230737"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/c/c3/2863.png/revision/latest?cb=20160123230737" class="image"><img alt="2863" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/c/c3/2863.png/revision/latest?cb=20160123230737" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2863.png" data-image-key="2863.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/c/c3/2863.png/revision/latest?cb=20160123230737" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Toy_Freddy" title="Adventure Toy Freddy">Toy Freddy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/7/74/Toy_bonnie.png/revision/latest?cb=20160214140556" class="image"><img alt="Toy bonnie" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/7/74/Toy_bonnie.png/revision/latest?cb=20160214140556" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Toy bonnie.png" data-image-key="Toy_bonnie.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/7/74/Toy_bonnie.png/revision/latest?cb=20160214140556"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/7/74/Toy_bonnie.png/revision/latest?cb=20160214140556" class="image"><img alt="Toy bonnie" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/7/74/Toy_bonnie.png/revision/latest?cb=20160214140556" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Toy bonnie.png" data-image-key="Toy_bonnie.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/7/74/Toy_bonnie.png/revision/latest?cb=20160214140556" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Toy_Bonnie" title="Adventure Toy Bonnie">Toy Bonnie</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/45/2385.png/revision/latest?cb=20160123222811" class="image"><img alt="2385" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/45/2385.png/revision/latest?cb=20160123222811" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2385.png" data-image-key="2385.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/45/2385.png/revision/latest?cb=20160123222811"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/45/2385.png/revision/latest?cb=20160123222811" class="image"><img alt="2385" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/45/2385.png/revision/latest?cb=20160123222811" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2385.png" data-image-key="2385.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/45/2385.png/revision/latest?cb=20160123222811" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Toy_Chica" class="mw-redirect" title="Adventure Toy Chica">Toy Chica</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/1a/2864.png/revision/latest?cb=20160123230514" class="image"><img alt="2864" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/1a/2864.png/revision/latest?cb=20160123230514" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2864.png" data-image-key="2864.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/1a/2864.png/revision/latest?cb=20160123230514"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/1a/2864.png/revision/latest?cb=20160123230514" class="image"><img alt="2864" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/1a/2864.png/revision/latest?cb=20160123230514" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2864.png" data-image-key="2864.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/1a/2864.png/revision/latest?cb=20160123230514" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Mangle" title="Adventure Mangle">Mangle</a></p> 		 	</figcaption> </figure></div>
</td></tr>
<tr>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/Bb.png/revision/latest?cb=20151214210513" class="image"><img alt="Bb" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/Bb.png/revision/latest?cb=20151214210513" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Bb.png" data-image-key="Bb.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/Bb.png/revision/latest?cb=20151214210513"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/Bb.png/revision/latest?cb=20151214210513" class="image"><img alt="Bb" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/Bb.png/revision/latest?cb=20151214210513" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Bb.png" data-image-key="Bb.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/Bb.png/revision/latest?cb=20151214210513" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Balloon_Boy" title="Adventure Balloon Boy">Balloon Boy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/ac/2885.png/revision/latest?cb=20160123230352" class="image"><img alt="2885" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/ac/2885.png/revision/latest?cb=20160123230352" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2885.png" data-image-key="2885.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/ac/2885.png/revision/latest?cb=20160123230352"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/ac/2885.png/revision/latest?cb=20160123230352" class="image"><img alt="2885" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/ac/2885.png/revision/latest?cb=20160123230352" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2885.png" data-image-key="2885.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/ac/2885.png/revision/latest?cb=20160123230352" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_JJ" title="Adventure JJ">JJ</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/16/2886.png/revision/latest?cb=20160810163655" class="image"><img alt="2886" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/16/2886.png/revision/latest?cb=20160810163655" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2886.png" data-image-key="2886.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/16/2886.png/revision/latest?cb=20160810163655"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/16/2886.png/revision/latest?cb=20160810163655" class="image"><img alt="2886" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/16/2886.png/revision/latest?cb=20160810163655" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2886.png" data-image-key="2886.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/16/2886.png/revision/latest?cb=20160810163655" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Phantom_Freddy" title="Adventure Phantom Freddy">Phantom Freddy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3b/2908.png/revision/latest?cb=20160123230244" class="image"><img alt="2908" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3b/2908.png/revision/latest?cb=20160123230244" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2908.png" data-image-key="2908.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3b/2908.png/revision/latest?cb=20160123230244"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3b/2908.png/revision/latest?cb=20160123230244" class="image"><img alt="2908" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3b/2908.png/revision/latest?cb=20160123230244" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2908.png" data-image-key="2908.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3b/2908.png/revision/latest?cb=20160123230244" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Phantom_Chica" title="Adventure Phantom Chica">Phantom Chica</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/bc/2909.png/revision/latest?cb=20160123230206" class="image"><img alt="2909" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/bc/2909.png/revision/latest?cb=20160123230206" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2909.png" data-image-key="2909.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/bc/2909.png/revision/latest?cb=20160123230206"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/bc/2909.png/revision/latest?cb=20160123230206" class="image"><img alt="2909" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/bc/2909.png/revision/latest?cb=20160123230206" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2909.png" data-image-key="2909.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/bc/2909.png/revision/latest?cb=20160123230206" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Phantom_Balloon_Boy" title="Adventure Phantom Balloon Boy">Phantom Balloon Boy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/32/2910.png/revision/latest?cb=20160123230134" class="image"><img alt="2910" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/32/2910.png/revision/latest?cb=20160123230134" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2910.png" data-image-key="2910.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/32/2910.png/revision/latest?cb=20160123230134"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/32/2910.png/revision/latest?cb=20160123230134" class="image"><img alt="2910" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/32/2910.png/revision/latest?cb=20160123230134" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2910.png" data-image-key="2910.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/32/2910.png/revision/latest?cb=20160123230134" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Phantom_Foxy" title="Adventure Phantom Foxy">Phantom Foxy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4d/2911.png/revision/latest?cb=20160123230030" class="image"><img alt="2911" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4d/2911.png/revision/latest?cb=20160123230030" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2911.png" data-image-key="2911.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4d/2911.png/revision/latest?cb=20160123230030"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4d/2911.png/revision/latest?cb=20160123230030" class="image"><img alt="2911" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4d/2911.png/revision/latest?cb=20160123230030" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2911.png" data-image-key="2911.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4d/2911.png/revision/latest?cb=20160123230030" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Phantom_Mangle" title="Adventure Phantom Mangle">Phantom Mangle</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/07/2912.png/revision/latest?cb=20160123225934" class="image"><img alt="2912" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/07/2912.png/revision/latest?cb=20160123225934" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2912.png" data-image-key="2912.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/07/2912.png/revision/latest?cb=20160123225934"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/07/2912.png/revision/latest?cb=20160123225934" class="image"><img alt="2912" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/07/2912.png/revision/latest?cb=20160123225934" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2912.png" data-image-key="2912.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/07/2912.png/revision/latest?cb=20160123225934" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Withered_Bonnie" title="Adventure Withered Bonnie">Withered Bonnie</a></p> 		 	</figcaption> </figure></div>
</td></tr>
<tr>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/95/WChicaicon.png/revision/latest?cb=20151214075311" class="image"><img alt="WChicaicon" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/95/WChicaicon.png/revision/latest?cb=20151214075311" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="WChicaicon.png" data-image-key="WChicaicon.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/95/WChicaicon.png/revision/latest?cb=20151214075311"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/95/WChicaicon.png/revision/latest?cb=20151214075311" class="image"><img alt="WChicaicon" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/95/WChicaicon.png/revision/latest?cb=20151214075311" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="WChicaicon.png" data-image-key="WChicaicon.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/95/WChicaicon.png/revision/latest?cb=20151214075311" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Withered_Chica" title="Adventure Withered Chica">Withered Chica</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/2914.png/revision/latest?cb=20160123225844" class="image"><img alt="2914" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/2914.png/revision/latest?cb=20160123225844" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2914.png" data-image-key="2914.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/2914.png/revision/latest?cb=20160123225844"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/2914.png/revision/latest?cb=20160123225844" class="image"><img alt="2914" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/2914.png/revision/latest?cb=20160123225844" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2914.png" data-image-key="2914.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/2914.png/revision/latest?cb=20160123225844" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Withered_Freddy" title="Adventure Withered Freddy">Withered Freddy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/WFoxyicon.png/revision/latest?cb=20151214075310" class="image"><img alt="WFoxyicon" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/WFoxyicon.png/revision/latest?cb=20151214075310" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="WFoxyicon.png" data-image-key="WFoxyicon.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/WFoxyicon.png/revision/latest?cb=20151214075310"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/WFoxyicon.png/revision/latest?cb=20151214075310" class="image"><img alt="WFoxyicon" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/WFoxyicon.png/revision/latest?cb=20151214075310" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="WFoxyicon.png" data-image-key="WFoxyicon.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/WFoxyicon.png/revision/latest?cb=20151214075310" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Withered_Foxy" title="Adventure Withered Foxy">Withered Foxy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/27/2916.png/revision/latest?cb=20160123225743" class="image"><img alt="2916" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/27/2916.png/revision/latest?cb=20160123225743" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2916.png" data-image-key="2916.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/27/2916.png/revision/latest?cb=20160123225743"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/27/2916.png/revision/latest?cb=20160123225743" class="image"><img alt="2916" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/27/2916.png/revision/latest?cb=20160123225743" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2916.png" data-image-key="2916.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/27/2916.png/revision/latest?cb=20160123225743" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Shadow_Freddy" title="Adventure Shadow Freddy">Shadow Freddy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/dc/2918.png/revision/latest?cb=20160123225724" class="image"><img alt="2918" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/dc/2918.png/revision/latest?cb=20160123225724" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="2918.png" data-image-key="2918.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/dc/2918.png/revision/latest?cb=20160123225724"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/dc/2918.png/revision/latest?cb=20160123225724" class="image"><img alt="2918" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/dc/2918.png/revision/latest?cb=20160123225724" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="2918.png" data-image-key="2918.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/dc/2918.png/revision/latest?cb=20160123225724" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Marionette" title="Adventure Marionette">Marionette</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/65/3007.png/revision/latest?cb=20160123225541" class="image"><img alt="3007" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/65/3007.png/revision/latest?cb=20160123225541" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3007.png" data-image-key="3007.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/65/3007.png/revision/latest?cb=20160123225541"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/65/3007.png/revision/latest?cb=20160123225541" class="image"><img alt="3007" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/65/3007.png/revision/latest?cb=20160123225541" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3007.png" data-image-key="3007.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/65/3007.png/revision/latest?cb=20160123225541" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Phantom_Marionette" title="Adventure Phantom Marionette">Phantom Marionette</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/a9/3008.png/revision/latest?cb=20160123225425" class="image"><img alt="3008" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/a9/3008.png/revision/latest?cb=20160123225425" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3008.png" data-image-key="3008.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/a9/3008.png/revision/latest?cb=20160123225425"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/a9/3008.png/revision/latest?cb=20160123225425" class="image"><img alt="3008" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/a9/3008.png/revision/latest?cb=20160123225425" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3008.png" data-image-key="3008.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/a/a9/3008.png/revision/latest?cb=20160123225425" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Golden_Freddy" title="Adventure Golden Freddy">Golden Freddy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/94/3010.png/revision/latest?cb=20160131021625" class="image"><img alt="3010" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/94/3010.png/revision/latest?cb=20160131021625" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3010.png" data-image-key="3010.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/94/3010.png/revision/latest?cb=20160131021625"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/94/3010.png/revision/latest?cb=20160131021625" class="image"><img alt="3010" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/94/3010.png/revision/latest?cb=20160131021625" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3010.png" data-image-key="3010.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/94/3010.png/revision/latest?cb=20160131021625" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Paperpals" title="Adventure Paperpals">Paperpals</a></p> 		 	</figcaption> </figure></div>
</td></tr>
<tr>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/3011.png/revision/latest?cb=20160123224351" class="image"><img alt="3011" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/3011.png/revision/latest?cb=20160123224351" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3011.png" data-image-key="3011.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/3011.png/revision/latest?cb=20160123224351"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/3011.png/revision/latest?cb=20160123224351" class="image"><img alt="3011" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/3011.png/revision/latest?cb=20160123224351" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3011.png" data-image-key="3011.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/0f/3011.png/revision/latest?cb=20160123224351" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Nightmare_Freddy" title="Adventure Nightmare Freddy">Nightmare Freddy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/f/ff/3012.png/revision/latest?cb=20160123224300" class="image"><img alt="3012" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/f/ff/3012.png/revision/latest?cb=20160123224300" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3012.png" data-image-key="3012.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/f/ff/3012.png/revision/latest?cb=20160123224300"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/f/ff/3012.png/revision/latest?cb=20160123224300" class="image"><img alt="3012" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/f/ff/3012.png/revision/latest?cb=20160123224300" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3012.png" data-image-key="3012.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/f/ff/3012.png/revision/latest?cb=20160123224300" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Nightmare_Bonnie" title="Adventure Nightmare Bonnie">Nightmare Bonnie</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/ed/3013.png/revision/latest?cb=20160123224235" class="image"><img alt="3013" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/ed/3013.png/revision/latest?cb=20160123224235" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3013.png" data-image-key="3013.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/ed/3013.png/revision/latest?cb=20160123224235"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/ed/3013.png/revision/latest?cb=20160123224235" class="image"><img alt="3013" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/ed/3013.png/revision/latest?cb=20160123224235" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3013.png" data-image-key="3013.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/ed/3013.png/revision/latest?cb=20160123224235" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Nightmare_Chica" title="Adventure Nightmare Chica">Nightmare Chica</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3f/3014.png/revision/latest?cb=20160123224153" class="image"><img alt="3014" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3f/3014.png/revision/latest?cb=20160123224153" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3014.png" data-image-key="3014.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3f/3014.png/revision/latest?cb=20160123224153"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3f/3014.png/revision/latest?cb=20160123224153" class="image"><img alt="3014" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3f/3014.png/revision/latest?cb=20160123224153" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3014.png" data-image-key="3014.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/3f/3014.png/revision/latest?cb=20160123224153" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Nightmare_Foxy" title="Adventure Nightmare Foxy">Nightmare Foxy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/3015.png/revision/latest?cb=20160123224110" class="image"><img alt="3015" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/3015.png/revision/latest?cb=20160123224110" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3015.png" data-image-key="3015.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/3015.png/revision/latest?cb=20160123224110"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/3015.png/revision/latest?cb=20160123224110" class="image"><img alt="3015" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/3015.png/revision/latest?cb=20160123224110" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3015.png" data-image-key="3015.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/10/3015.png/revision/latest?cb=20160123224110" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Endo-01" title="Adventure Endo-01">Endo-01</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/49/3016.png/revision/latest?cb=20160123224017" class="image"><img alt="3016" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/49/3016.png/revision/latest?cb=20160123224017" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3016.png" data-image-key="3016.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/49/3016.png/revision/latest?cb=20160123224017"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/49/3016.png/revision/latest?cb=20160123224017" class="image"><img alt="3016" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/49/3016.png/revision/latest?cb=20160123224017" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3016.png" data-image-key="3016.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/49/3016.png/revision/latest?cb=20160123224017" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Endo-02" title="Adventure Endo-02">Endo-02</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2b/3017.png/revision/latest?cb=20160123223911" class="image"><img alt="3017" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2b/3017.png/revision/latest?cb=20160123223911" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3017.png" data-image-key="3017.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2b/3017.png/revision/latest?cb=20160123223911"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2b/3017.png/revision/latest?cb=20160123223911" class="image"><img alt="3017" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2b/3017.png/revision/latest?cb=20160123223911" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3017.png" data-image-key="3017.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2b/3017.png/revision/latest?cb=20160123223911" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Plushtrap" title="Adventure Plushtrap">Plushtrap</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/02/3018.png/revision/latest?cb=20160123223754" class="image"><img alt="3018" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/02/3018.png/revision/latest?cb=20160123223754" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3018.png" data-image-key="3018.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/02/3018.png/revision/latest?cb=20160123223754"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/02/3018.png/revision/latest?cb=20160123223754" class="image"><img alt="3018" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/02/3018.png/revision/latest?cb=20160123223754" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3018.png" data-image-key="3018.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/0/02/3018.png/revision/latest?cb=20160123223754" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Endoplush" title="Adventure Endoplush">Endoplush</a></p> 		 	</figcaption> </figure></div>
</td></tr>
<tr>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2e/3019.png/revision/latest?cb=20160123223723" class="image"><img alt="3019" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2e/3019.png/revision/latest?cb=20160123223723" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3019.png" data-image-key="3019.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2e/3019.png/revision/latest?cb=20160123223723"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2e/3019.png/revision/latest?cb=20160123223723" class="image"><img alt="3019" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2e/3019.png/revision/latest?cb=20160123223723" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3019.png" data-image-key="3019.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2e/3019.png/revision/latest?cb=20160123223723" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Springtrap" title="Adventure Springtrap">Springtrap</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/30/3020.png/revision/latest?cb=20160123223648" class="image"><img alt="3020" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/30/3020.png/revision/latest?cb=20160123223648" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3020.png" data-image-key="3020.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/30/3020.png/revision/latest?cb=20160123223648"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/30/3020.png/revision/latest?cb=20160123223648" class="image"><img alt="3020" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/30/3020.png/revision/latest?cb=20160123223648" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3020.png" data-image-key="3020.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/30/3020.png/revision/latest?cb=20160123223648" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_RWQFSFASXC" title="Adventure RWQFSFASXC">RWQFSFASXC (Shadow Bonnie)</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/123456789.png/revision/latest?cb=20160123223100" class="image"><img alt="123456789" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/123456789.png/revision/latest?cb=20160123223100" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="123456789.png" data-image-key="123456789.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/123456789.png/revision/latest?cb=20160123223100"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/123456789.png/revision/latest?cb=20160123223100" class="image"><img alt="123456789" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/123456789.png/revision/latest?cb=20160123223100" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="123456789.png" data-image-key="123456789.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b6/123456789.png/revision/latest?cb=20160123223100" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Crying_Child" title="Adventure Crying Child">Crying Child</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/3022.png/revision/latest?cb=20160123223623" class="image"><img alt="3022" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/3022.png/revision/latest?cb=20160123223623" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3022.png" data-image-key="3022.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/3022.png/revision/latest?cb=20160123223623"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/3022.png/revision/latest?cb=20160123223623" class="image"><img alt="3022" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/3022.png/revision/latest?cb=20160123223623" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3022.png" data-image-key="3022.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/9/90/3022.png/revision/latest?cb=20160123223623" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Funtime_Foxy" title="Adventure Funtime Foxy">Funtime Foxy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/88/3023.png/revision/latest?cb=20160123223533" class="image"><img alt="3023" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/88/3023.png/revision/latest?cb=20160123223533" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3023.png" data-image-key="3023.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/88/3023.png/revision/latest?cb=20160123223533"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/88/3023.png/revision/latest?cb=20160123223533" class="image"><img alt="3023" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/88/3023.png/revision/latest?cb=20160123223533" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3023.png" data-image-key="3023.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/88/3023.png/revision/latest?cb=20160123223533" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Nightmare_Fredbear" title="Adventure Nightmare Fredbear">Nightmare Fredbear</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2d/3024.png/revision/latest?cb=20160123223350" class="image"><img alt="3024" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2d/3024.png/revision/latest?cb=20160123223350" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3024.png" data-image-key="3024.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2d/3024.png/revision/latest?cb=20160123223350"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2d/3024.png/revision/latest?cb=20160123223350" class="image"><img alt="3024" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2d/3024.png/revision/latest?cb=20160123223350" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3024.png" data-image-key="3024.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/2/2d/3024.png/revision/latest?cb=20160123223350" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Nightmare" title="Adventure Nightmare">Nightmare</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/5/5a/3025.png/revision/latest?cb=20160123223329" class="image"><img alt="3025" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/5/5a/3025.png/revision/latest?cb=20160123223329" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3025.png" data-image-key="3025.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/5/5a/3025.png/revision/latest?cb=20160123223329"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/5/5a/3025.png/revision/latest?cb=20160123223329" class="image"><img alt="3025" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/5/5a/3025.png/revision/latest?cb=20160123223329" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3025.png" data-image-key="3025.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/5/5a/3025.png/revision/latest?cb=20160123223329" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Fredbear" title="Adventure Fredbear">Fredbear</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e0/3026.png/revision/latest?cb=20160123223303" class="image"><img alt="3026" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e0/3026.png/revision/latest?cb=20160123223303" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="3026.png" data-image-key="3026.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e0/3026.png/revision/latest?cb=20160123223303"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e0/3026.png/revision/latest?cb=20160123223303" class="image"><img alt="3026" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e0/3026.png/revision/latest?cb=20160123223303" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="3026.png" data-image-key="3026.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e0/3026.png/revision/latest?cb=20160123223303" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Spring_Bonnie" title="Adventure Spring Bonnie">Spring Bonnie</a></p> 		 	</figcaption> </figure></div>
</td></tr></tbody></table><table class="wikitable">
<tbody><tr>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/39/Adventure_Jack-O-Bonnie.png/revision/latest?cb=20160422224618" class="image"><img alt="Adventure Jack-O-Bonnie" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/39/Adventure_Jack-O-Bonnie.png/revision/latest?cb=20160422224618" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Adventure Jack-O-Bonnie.png" data-image-key="Adventure_Jack-O-Bonnie.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/39/Adventure_Jack-O-Bonnie.png/revision/latest?cb=20160422224618"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/39/Adventure_Jack-O-Bonnie.png/revision/latest?cb=20160422224618" class="image"><img alt="Adventure Jack-O-Bonnie" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/39/Adventure_Jack-O-Bonnie.png/revision/latest?cb=20160422224618" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Adventure Jack-O-Bonnie.png" data-image-key="Adventure_Jack-O-Bonnie.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/3/39/Adventure_Jack-O-Bonnie.png/revision/latest?cb=20160422224618" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Jack-O-Bonnie" title="Adventure Jack-O-Bonnie">Jack-O-Bonnie</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b7/Adventure_Jack-O-Chica.png/revision/latest?cb=20160422224639" class="image"><img alt="Adventure Jack-O-Chica" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b7/Adventure_Jack-O-Chica.png/revision/latest?cb=20160422224639" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Adventure Jack-O-Chica.png" data-image-key="Adventure_Jack-O-Chica.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b7/Adventure_Jack-O-Chica.png/revision/latest?cb=20160422224639"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b7/Adventure_Jack-O-Chica.png/revision/latest?cb=20160422224639" class="image"><img alt="Adventure Jack-O-Chica" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b7/Adventure_Jack-O-Chica.png/revision/latest?cb=20160422224639" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Adventure Jack-O-Chica.png" data-image-key="Adventure_Jack-O-Chica.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/b/b7/Adventure_Jack-O-Chica.png/revision/latest?cb=20160422224639" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Jack-O-Chica" title="Adventure Jack-O-Chica">Jack-O-Chica</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/d2/Scott.png/revision/latest?cb=20160422225910" class="image"><img alt="Scott" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/d2/Scott.png/revision/latest?cb=20160422225910" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Scott.png" data-image-key="Scott.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/d2/Scott.png/revision/latest?cb=20160422225910"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/d2/Scott.png/revision/latest?cb=20160422225910" class="image"><img alt="Scott" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/d2/Scott.png/revision/latest?cb=20160422225910" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Scott.png" data-image-key="Scott.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/d/d2/Scott.png/revision/latest?cb=20160422225910" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Animdude" title="Adventure Animdude">Animdude</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/63/Chipper.png/revision/latest?cb=20160422225833" class="image"><img alt="Chipper" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/63/Chipper.png/revision/latest?cb=20160422225833" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Chipper.png" data-image-key="Chipper.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/63/Chipper.png/revision/latest?cb=20160422225833"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/63/Chipper.png/revision/latest?cb=20160422225833" class="image"><img alt="Chipper" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/63/Chipper.png/revision/latest?cb=20160422225833" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Chipper.png" data-image-key="Chipper.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/6/63/Chipper.png/revision/latest?cb=20160422225833" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Chipper" class="mw-redirect" title="Adventure Chipper">Chipper</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/14/Adventure_Nightmare_Balloon_Boy.png/revision/latest?cb=20160422224701" class="image"><img alt="Adventure Nightmare Balloon Boy" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/14/Adventure_Nightmare_Balloon_Boy.png/revision/latest?cb=20160422224701" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Adventure Nightmare Balloon Boy.png" data-image-key="Adventure_Nightmare_Balloon_Boy.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/14/Adventure_Nightmare_Balloon_Boy.png/revision/latest?cb=20160422224701"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/14/Adventure_Nightmare_Balloon_Boy.png/revision/latest?cb=20160422224701" class="image"><img alt="Adventure Nightmare Balloon Boy" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/14/Adventure_Nightmare_Balloon_Boy.png/revision/latest?cb=20160422224701" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Adventure Nightmare Balloon Boy.png" data-image-key="Adventure_Nightmare_Balloon_Boy.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/1/14/Adventure_Nightmare_Balloon_Boy.png/revision/latest?cb=20160422224701" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Nightmare_Balloon_Boy" title="Adventure Nightmare Balloon Boy">Nightmare Balloon Boy</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4e/Adventure_Nightmarionne.png/revision/latest?cb=20160422224220" class="image"><img alt="Adventure Nightmarionne" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4e/Adventure_Nightmarionne.png/revision/latest?cb=20160422224220" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Adventure Nightmarionne.png" data-image-key="Adventure_Nightmarionne.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4e/Adventure_Nightmarionne.png/revision/latest?cb=20160422224220"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4e/Adventure_Nightmarionne.png/revision/latest?cb=20160422224220" class="image"><img alt="Adventure Nightmarionne" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4e/Adventure_Nightmarionne.png/revision/latest?cb=20160422224220" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Adventure Nightmarionne.png" data-image-key="Adventure_Nightmarionne.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/4/4e/Adventure_Nightmarionne.png/revision/latest?cb=20160422224220" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Nightmarionne" title="Adventure Nightmarionne">Nightmarionne</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e9/Coffee.png/revision/latest?cb=20160422225852" class="image"><img alt="Coffee" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e9/Coffee.png/revision/latest?cb=20160422225852" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Coffee.png" data-image-key="Coffee.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e9/Coffee.png/revision/latest?cb=20160422225852"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e9/Coffee.png/revision/latest?cb=20160422225852" class="image"><img alt="Coffee" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e9/Coffee.png/revision/latest?cb=20160422225852" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Coffee.png" data-image-key="Coffee.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/e/e9/Coffee.png/revision/latest?cb=20160422225852" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Coffee" title="Adventure Coffee">Coffee</a></p> 		 	</figcaption> </figure></div>
</td>
<td><div class="center" bis_skin_checked="1"><figure class="thumb tnone " style="width: 70px"> 	<a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/89/Adventure_Purple_Guy.png/revision/latest?cb=20160422225806" class="image"><img alt="Adventure Purple Guy" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/89/Adventure_Purple_Guy.png/revision/latest?cb=20160422225806" decoding="async" loading="lazy" width="70" height="70" class="thumbimage lazyloaded" data-image-name="Adventure Purple Guy.png" data-image-key="Adventure_Purple_Guy.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/89/Adventure_Purple_Guy.png/revision/latest?cb=20160422225806"></a> 	<noscript><a href="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/89/Adventure_Purple_Guy.png/revision/latest?cb=20160422225806" class="image"><img alt="Adventure Purple Guy" src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/89/Adventure_Purple_Guy.png/revision/latest?cb=20160422225806" decoding="async" loading="lazy" width="70" height="70" class="thumbimage" data-image-name="Adventure Purple Guy.png" data-image-key="Adventure_Purple_Guy.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/five-nights-at-freddys-world-world/images/8/89/Adventure_Purple_Guy.png/revision/latest?cb=20160422225806" /></a></noscript> 	<figcaption class="thumbcaption"> 		 		 		 			<p class="caption"><a href="/wiki/Adventure_Purple_Guy" class="mw-redirect" title="Adventure Purple Guy">Purple Guy</a></p> 		 	</figcaption> </figure></div>
</td></tr></tbody></table>'''

    folder_input = r'C:\Users\OscarStaniszewski\Desktop'  # Określenie folderu na pulpicie
    headshot_folder = os.path.join(folder_input, 'headshots')  # Folder do zapisania headshotów

    if not os.path.exists(headshot_folder):
        os.makedirs(headshot_folder)

    # Zbieranie URL do headshotów
    headshots = gather_headshot_urls(html_content)
    print(f"Znaleziono {len(headshots)} headshotów do pobrania.")

    for img_url, title in headshots:
        download_image(img_url, headshot_folder, title)